---
- hosts: localhost
  gather_facts: false
  vars_files:
    ./vars/defaults.yml
  tasks:
  - name: Get a tempfile for the htpasswd file
    ansible.builtin.tempfile:
      state: file
    register: httpasswd_temp

  - name: Create htpasswd user
    ansible.builtin.shell:
      htpasswd -c -B -b "{{ httpasswd_temp.path }}" "{{ internal_registry_user }}" "{{ internal_registry_pass }}"

  - name: Create OC secret
    ansible.builtin.shell: |
      set -e
      oc delete secret htpass-secret -n openshift-config
      oc create secret generic htpass-secret --from-file=htpasswd="{{ httpasswd_temp.path }}" -n openshift-config

  - name: Template Oauth template
    ansible.builtin.template:
      src: ./templates/htpasswd-oauth.yaml
      dest: /tmp/htpasswd-oauth.yaml

  - name: Apply oauth settings
    ansible.builtin.shell:
      oc apply -f /tmp/htpasswd-oauth.yaml
