- name: Check that KUBEADMINAPI, KUBEADMINPASS
  ansible.builtin.fail:
    msg: "KUBEADMINAPI: '{{ kubeadminapi }}', KUBEADMINPASS: '{{ kubeadminpass }}'. Both need to be set"
  failed_when: >
    (kubeadminapi is not defined or kubeadminapi | length == 0) or
    (kubeadminpass is not defined or kubeadminpass | length == 0)

- name: Login via kubeadmin
  ansible.builtin.shell: |
    oc login -u kubeadmin -p "{{ kubeadminpass }}" "{{ kubeadminapi }}"

- name: Get kubeadmin token
  ansible.builtin.shell: |
    oc whoami -t
  register: oc_whoami_raw

- name: Set kubeadmin token
  ansible.builtin.set_fact:
    kubeadmin_token: "{{ oc_whoami_raw.stdout }}"

- name: Expose internal registry route
  ansible.builtin.shell: |
    oc patch configs.imageregistry.operator.openshift.io/cluster --patch '{"spec":{"defaultRoute":true}}' --type=merge

- name: Fetch internal registry route value
  ansible.builtin.shell:
    oc registry info --public=true
  register: registry_route_raw

- name: Set route fact
  ansible.builtin.set_fact:
    registry_route: "{{ registry_route_raw.stdout }}"

- name: Set registry allowedRegistries
  ansible.builtin.shell: >
    oc patch image.config.openshift.io/cluster --patch "{\"spec\":{\"registrySources\":{\"allowedRegistries\":[ \"quay.io\", \"registry.redhat.io\",
    \"registry-proxy.engineering.redhat.com\", \"image-registry.openshift-image-registry.svc:5000\", \"{{ registry_route }}\"]}}}" --type=merge

- name: Set registry insecureRegistries
  ansible.builtin.shell: >
    oc patch image.config.openshift.io/cluster --patch "{\"spec\":{\"registrySources\":{\"insecureRegistries\":[ \"registry-proxy.engineering.redhat.com\",
    \"image-registry.openshift-image-registry.svc:5000\", \"{{ registry_route }}\"]}}}" --type=merge

- name: Get current cluster pull secrets
  ansible.builtin.shell:
    oc extract secret/pull-secret -n openshift-config --to=-
  register: pull_secrets_raw

- name: Add local registry to pull secrets and set auth fact
  ansible.builtin.set_fact:
    pull_secrets_new: "{{ pull_secrets_raw.stdout | from_json }}"
    internal_registry_auth: "{{ ('kubeadmin:' + kubeadmin_token) | b64encode }}"

- name: Add local registry to pull secrets
  ansible.builtin.set_fact:
    pull_secrets: "{{ pull_secrets_new | combine({'auths': { registry_route: { 'email': internal_registry_email, 'auth': internal_registry_auth }}}, recursive=true) }}"

- name: Get a tempfile for the pull secrets
  ansible.builtin.tempfile:
    state: directory
  register: pull_secrets_tempfolder

- name: Store pull secrets in tempfile
  ansible.builtin.copy:
    dest: "{{ pull_secrets_tempfolder.path }}/.dockerconfigjson"
    content: "{{ pull_secrets | to_nice_json }}"

- name: Update pull-secret in the cluster
  ansible.builtin.shell: |
    oc set data secret/pull-secret -n openshift-config --from-file="{{ pull_secrets_tempfolder.path }}/.dockerconfigjson"

- name: Login the internal registry with podman
  ansible.builtin.shell:
    podman login --tls-verify=false --username unused --password "{{ kubeadmin_token }}" "https://{{ registry_route }}"

- name: Remove tempfile
  ansible.builtin.file:
    path: "{{ pull_secrets_tempfolder.path }}"
    state: absent

- name: Set Mirror URL fact for internal mirror
  ansible.builtin.set_fact:
    mirror_target: "{{ registry_route }}/{{ internal_registry_ns }}/iib"

