- name: Check that INTERNAL_REGISTRY_PASS is set
  ansible.builtin.fail:
    msg: "INTERNAL_REGISTRY_PASS: '{{ internal_registry_pass }}' is not set"
  failed_when: internal_registry_pass is not defined or internal_registry_pass | length == 0

- name: Expose internal registry route
  ansible.builtin.shell: |
    oc patch configs.imageregistry.operator.openshift.io/cluster --patch '{"spec":{"defaultRoute":true}}' --type=merge

- name: Fetch internal registry route value
  ansible.builtin.shell:
    oc registry info --public=true
  register: registry_route_raw
  retries: 20
  delay: 10
  until:
  - registry_route_raw is not failed
  - registry_route_raw.stdout | length > 0

- name: Set route fact
  ansible.builtin.set_fact:
    registry_route: "{{ registry_route_raw.stdout }}"

- name: Set registry allowedRegistries
  ansible.builtin.shell: >
    oc patch image.config.openshift.io/cluster --patch "{\"spec\":{\"registrySources\":{\"allowedRegistries\":[ \"quay.io\", \"registry.redhat.io\",
    \"registry-proxy.engineering.redhat.com\", \"image-registry.openshift-image-registry.svc:5000\", \"{{ registry_route }}\"]}}}" --type=merge

- name: Set registry insecureRegistries
  ansible.builtin.shell: >
    oc patch image.config.openshift.io/cluster --patch "{\"spec\":{\"registrySources\":{\"insecureRegistries\":[ \"registry-proxy.engineering.redhat.com\",
    \"image-registry.openshift-image-registry.svc:5000\", \"{{ registry_route }}\"]}}}" --type=merge

- name: Get a tempfile for the htpasswd file
  ansible.builtin.tempfile:
    state: file
  register: httpasswd_temp

- name: Create htpasswd user
  ansible.builtin.shell:
    htpasswd -c -B -b "{{ httpasswd_temp.path }}" "{{ internal_registry_user }}" "{{ internal_registry_pass }}"

- name: Delete OC secret
  ansible.builtin.shell: |
    oc delete secret htpass-secret -n openshift-config
  failed_when: false

- name: Create OC secret
  ansible.builtin.shell: |
    oc create secret generic htpass-secret --from-file=htpasswd="{{ httpasswd_temp.path }}" -n openshift-config

- name: Template Oauth template
  ansible.builtin.template:
    src: ./templates/htpasswd-oauth.yaml
    dest: /tmp/htpasswd-oauth.yaml

- name: Apply oauth settings
  ansible.builtin.shell:
    oc apply -f /tmp/htpasswd-oauth.yaml

- name: Add local registry to pull secrets and set auth fact
  ansible.builtin.set_fact:
    pull_secrets_new: "{{ pull_secrets_raw.stdout | from_json }}"
    internal_registry_auth: "{{ (internal_registry_user ':' + registry_token) | b64encode }}"

- name: Get current cluster pull secrets
  ansible.builtin.shell:
    oc extract secret/pull-secret -n openshift-config --to=-
  register: pull_secrets_raw

- name: Login to "{{ internal_registry_user }}"
  ansible.builtin.shell:
    oc login -u "{{ internal_registry_user }}" -p"{{ internal_registry_pass }}"
  retries: 20
  delay: 30
  register: registry_login
  until: registry_login is not failed

- name: Get "{{ internal_registry_user }}" token
  ansible.builtin.shell:
    oc whoami -t
  register: registry_token_raw

- name: Set registry user token
  ansible.builtin.set_fact:
    registry_token: "{{ registry_token_raw.stdout }}"

- name: Add local registry to pull secrets
  ansible.builtin.set_fact:
    pull_secrets: "{{ pull_secrets_new | combine({'auths': { registry_route: { 'email': internal_registry_email, 'auth': internal_registry_auth }}}, recursive=true) }}"

- name: Log out "{{ internal_registry_user }}" user
  ansible.builtin.shell:
    oc logout "{{ internal_registry_user }}"

- name: Get a tempfile for the pull secrets
  ansible.builtin.tempfile:
    state: directory
  register: pull_secrets_tempfolder

- name: Store pull secrets in tempfile
  ansible.builtin.copy:
    dest: "{{ pull_secrets_tempfolder.path }}/.dockerconfigjson"
    content: "{{ pull_secrets | to_nice_json }}"

- name: Update pull-secret in the cluster
  ansible.builtin.shell: |
    oc set data secret/pull-secret -n openshift-config --from-file="{{ pull_secrets_tempfolder.path }}/.dockerconfigjson"

- name: Before proceeding here we need to make sure that the MCPs have all settled
  ansible.builtin.shell: |
    if [ $(oc get mcp/master -o jsonpath='{.status.readyMachineCount}') != $(oc get mcp/master -o jsonpath='{.status.machineCount}') ]; then
      exit 1
    fi
    if [ $(oc get mcp/worker -o jsonpath='{.status.readyMachineCount}') != $(oc get mcp/worker -o jsonpath='{.status.machineCount}') ]; then
      exit 1
    fi
  retries: 30
  delay: 20
  register: mcp_ready
  until: mcp_ready is not failed

- name: Login the internal registry with podman
  ansible.builtin.shell:
    podman login --tls-verify=false --username unused --password "{{ registry_token }}" "https://{{ registry_route }}"

- name: Set Mirror URL fact for internal mirror IIB
  ansible.builtin.set_fact:
    mirror_iib: "{{ registry_route }}/{{ internal_registry_ns }}/iib"

- name: Set Mirror URL fact for internal mirror
  ansible.builtin.set_fact:
    mirror_dest: "{{ registry_route }}/{{ internal_registry_ns }}/"
